---
name: phplinter
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: 
          echo "ğŸ‰ New job triggered by a ${{ github.event_name }} event."
      - run: 
          echo "ğŸ§ Job is now running on ${{ runner.os }} - hosted by GitHub!"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: 
          echo "ğŸ’¡ Cloned ${{ github.repository }} repository."
      - name: Super-Linter
        uses: github/super-linter@v4.9.7
      - run: echo "ğŸ This job's status is ${{ job.status }}."
